### ISSUE TITLE
请问为什么要把属性这样扩展起来

### ISSUE THREAD

**Issue by zhengkai85** [Josin22/JSLoadMoreService#2]
- (BOOL)isNoMoreData{ return [objc_getAssociatedObject(self, &key_isNoMoreData) boolValue]; } - (void)setIsNoMoreData:(BOOL)isNoMoreData{ objc_setAssociatedObject(self, &key_isNoMoreData, @(isNoMoreData), OBJC_ASSOCIATION_ASSIGN); } 请问为什么要把属性这样扩展起来，有什么好处吗？不扩展使用有影响？

**Comment by Josin22** [comment]
不扩展就需要整个类、属性,然后你集成整个类,相比较下,这种方案会比较友好
